NEW Session grant files without permissions
silverstripe-labs/silverstripe-sharedraftcontent pull request #150
Opened 2021-08-18 01:40 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/132

2021-10-12 23:46 UTC, emteknetnz reviewed
Should target 2 since there's new API

2021-10-12 23:59 UTC, andrewandante approved these changes
Looks good to me 😄

2022-03-02 03:02 UTC, michalkleiner requested changes

2022-03-02 03:02 UTC, michalkleiner commented on .travis.yml
> +    - REQUIRE_RECIPE="4.x-dev || "
```suggestion
    - REQUIRE_RECIPE="4.10.x-dev || "
```

2022-03-02 03:02 UTC, michalkleiner commented on .travis.yml
> +    - REQUIRE_RECIPE="4.x-dev || "
Framework 4.10 and Assets 1.10 do exist now, should we adjust here?

2022-03-02 03:04 UTC, michalkleiner approved these changes
Merge on green

2022-03-02 04:14 UTC, merged