Bugfix: Infinite recursion sanity checks with more helpful error messages
silverstripe-labs/silverstripe-sharedraftcontent pull request #214
Opened 2023-10-16 00:48 UTC by nathanbrauer

The following snippet in `ShareDraftController.php` at L161 includes no sanity checks to prevent infinite recursions when it attempts to follow redirects internally via recursions.

https://github.com/silverstripe/silverstripe-sharedraftcontent/blob/7c3f7e7f75883d1d7790bdd2e6a646a86901e5e4/src/Controllers/ShareDraftController.php#L137-L165

Infinite recursions, such as those experienced in #213, would previously cause fatal time out or memory limit errors.

This pull request resolves this problem by adding sanity checks, preventing unanticipated internal infinite recursions via "logging" a minimal redirect stack to a private array on `ShareDraftController` and throws an Exception (with helpful information for developers) if....
1. ...a URL has already been processed for redirection (infinite recursion detected), OR
2. ...30 redirects have been logged 
  _(30 is an arbitrary number that seems to be more than what is typically necessary; this could, in a separate PR, be pulled into a config variable if desired)_

## Examples of Exception outputs

### Infinite recursion detected
![Screenshot from 2023-10-14 15-10-05](https://github.com/silverstripe/silverstripe-sharedraftcontent/assets/323945/6f9da94d-f423-45f3-9b59-18d709437244)

### Max redirect recursions reached
![Screenshot from 2023-10-14 15-09-30](https://github.com/silverstripe/silverstripe-sharedraftcontent/assets/323945/bb1c85e2-5084-45d0-acc6-64d45fccc8e3)

## Related 
- #213 

## Info

- Edits for maintainers are enabled 
- Set to merge into `2` and can be rebased onto `3` without issue

---
@muskie9

2023-10-16 01:24 UTC, nathanbrauer commented
Extracted some duplicate code to satisfy previously failed workflow

2023-11-09 01:41 UTC, emteknetnz requested changes

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +    private $redirectRecursionIterations = [];
```suggestion
    private array $redirectRecursionIterations = [];
```

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +                throw new \Exception("Infinite recursion detected.".$this->getRedirectRecursionIterationsLog($url));
```suggestion
                throw new \Exception("Infinite recursion detected." . $this->getRedirectRecursionIterationsLog($url));
```

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +                throw new \Exception("Max redirect recursions reached.".$this->getRedirectRecursionIterationsLog());
```suggestion
                throw new \Exception("Max redirect recursions reached." . $this->getRedirectRecursionIterationsLog());
```

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +    protected function getRedirectRecursionIterationsLog(string $append_url=''): string
```suggestion
    private function getRedirectRecursionIterationsLog(string $appendUrl= ''): string
```

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +     */
```suggestion
```

2023-11-09 01:41 UTC, emteknetnz commented on src/Controllers/ShareDraftController.php
> +            . ($append_url ? "\n$append_url" : '');
```suggestion
            . ($appendUrl ? "\n$appendUrl" : '');
```

2023-11-09 17:21 UTC, nathanbrauer commented on src/Controllers/ShareDraftController.php
> +     */
@emteknetnz - I'm a little confused why we're removing the docblock...

2023-11-09 22:53 UTC, emteknetnz approved these changes

2023-11-09 22:53 UTC, merged

2023-11-09 22:57 UTC, emteknetnz commented
I've merged this, though I noticed that it was targetting the `2` branch instead of the `2.9` branch, sorry I should have picked up as part of peer review

I've created a [backport PR](https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/217) to get this into `2.9` where I've cherry-picked the squahed merge commit.  Once that is merged it will be automatically tagged as 2.9.4

2023-11-10 00:16 UTC, nathanbrauer commented
Thanks for all your work to get this across the finish line, @emteknetnz!